[program:blood_label]
command=python3 /root/blood_label/server.py
directory=/root/blood_label
autostart=true
autorestart=true
stdout_logfile=/root/blood_label/server.log
stderr_logfile=/root/blood_label/server.log
